# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "simple-app"
client_id = "0b364b783bde0388a83e7adffa4b5673"
application_url = "https://equipped-recorders-investments-underlying.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://equipped-recorders-investments-underlying.trycloudflare.com/auth/callback",
  "https://equipped-recorders-investments-underlying.trycloudflare.com/auth/shopify/callback",
  "https://equipped-recorders-investments-underlying.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "vfortunato.myshopify.com"
